name: Komodo Linux CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 1'

jobs:

  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install deps (Linux)

        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                  build-essential \
                  pkg-config \
                  libc6-dev \
                  m4 \
                  g++-multilib \
                  autoconf \
                  libtool \
                  ncurses-dev \
                  unzip \
                  git \
                  python3 \
                  python3-zmq \
                  zlib1g-dev \
                  wget \
                  libcurl4-gnutls-dev \
                  bsdmainutils \
                  automake \
                  curl \
                  cmake \
                  mingw-w64 \
                  libsodium-dev \
                  libevent-dev  -y

      - name: Build (Linux)
        run: |
          # flag for some CC tests transactions - so DO NOT USE THIS CI ARTIFACTS IN PRODUCTION!!!
          CONFIGURE_FLAGS='CPPFLAGS=-DTESTMODE' ./zcutil/build.sh -j$(nproc)
          tar -czvf komodo-linux.tar.gz src/komodod src/komodo-cli

      - name: Upload komodo-linux.tar.gz as artifact
        uses: actions/upload-artifact@v1
        with:
          name: komodo-linux
          path: ./komodo-linux.tar.gz

  linux-test-dice-token-reards-faucet-cc:

    name: Test (Linux/Dice, Token, Faucet, Rewards)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v3

      - name: Install deps (Dice, Token, Faucet, Rewards CC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip
          python3 -m pip install wheel
          python3 -m pip install pytest wget jsonschema
          python3 -m pip install requests ujson

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Test CC (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh "cc_modules/test_dice.py cc_modules/test_faucet.py cc_modules/test_token.py cc_modules/test_rewards.py"

  linux-test-oracles:

    name: Test (Linux/OraclesCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v3

      - name: Install deps (OraclesCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip
          python3 -m pip install wheel
          python3 -m pip install pytest wget jsonschema
          python3 -m pip install requests ujson

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Oracles Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_oracles.py

  linux-test-baserpc:

    name: Test (Linux/BasicRPC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v3

      - name: Install deps (BasicRPC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip
          python3 -m pip install wheel
          python3 -m pip install pytest wget jsonschema
          python3 -m pip install requests ujson

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: BasicRPC Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh basic

  linux-test-channels:

    name: Test (Linux/ChannelsCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v3

      - name: Install deps (ChannelsCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip
          python3 -m pip install wheel
          python3 -m pip install pytest wget jsonschema
          python3 -m pip install requests ujson

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Channels Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_channels.py

  linux-test-heir:

    name: Test (Linux/HeirCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v3

      - name: Install deps (HeirCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip
          python3 -m pip install wheel
          python3 -m pip install pytest wget jsonschema
          python3 -m pip install requests ujson

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Heir Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_heir.py
